image:
  - Visual Studio 2017

environment:
  DEBUG_LOGGER: "1"
  matrix:
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"

build: off

install:
  - "%PYTHON%\\python.exe -m pip install pywin32"
  - copy tests\prog_AC.in tests\prog_AC.out

test_script:
  - "%PYTHON%\\python.exe -m unittest discover tests"

