image:
  - Visual Studio 2017

environment:
  DEBUG_LOGGER: "1"
  matrix:
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"

build: off

install:
  - "%PYTHON%\\python.exe -m pip install pywin32"

test_script:
  - type .\test_codes\prog_AC.out
  - "%PYTHON%\\python.exe -m unittest discover"

