image:
  - Visual Studio 2017

environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"

build: off

install:
  - "%PYTHON%\\python.exe -m pip install pywin32"

test_script:
  - "%PYTHON%\\python.exe -m unittest discover"

